INSERT INTO render_jobs (id, script_id, user_id, status) VALUES (
  'f1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c7',
  'e1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c6',
  '00000000-0000-0000-0000-000000000000',
  'complete'
) ON CONFLICT (id) DO UPDATE SET status = 'complete';

INSERT INTO rendered_segments (job_id, segment_id, status, dialogue, b_roll_image_url, ui_action_card) VALUES
('f1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c7', 1, 'complete', 'Good morning. It is Saturday, March 22nd. Clear skies, seventy-two degrees expected today. Winds light from the southwest. A strong day to move decisively — here is your operational briefing.', 'https://picsum.photos/seed/sunrise-city/1280/720', '{"is_active":true,"card_type":"summary","title":"Morning Situation Report","action_button_text":"View Full Brief","action_payload":"/your-brief","metadata":{"temp":"72F","condition":"Clear"}}'),
('f1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c7', 2, 'complete', 'Critical security alert: a zero-day authentication bypass has been disclosed in NextAuth.js, CVE-2026-4521, with a CVSS score of 9.8. Over twelve thousand applications are affected. Patches are available. Your security team should prioritize this immediately.', 'https://picsum.photos/seed/cybersec-ops/1280/720', '{"is_active":true,"card_type":"link_open","title":"Critical CVE Alert","action_button_text":"Review Advisory","action_payload":"https://thehackernews.com/2026/03/nextauth-zero-day","metadata":{"cve":"CVE-2026-4521","cvss":"9.8"}}'),
('f1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c7', 3, 'complete', 'Markets are surging. The S and P 500 hit an all-time high, driven by a 4.2 percent rally in AI stocks. NVIDIA is up 6.1 percent, Microsoft up 3.8 percent. Analysts point to aggressive AI infrastructure spending as the primary catalyst.', 'https://picsum.photos/seed/market-rally/1280/720', '{"is_active":true,"card_type":"link_open","title":"Market Rally Analysis","action_button_text":"Open Bloomberg","action_payload":"https://bloomberg.com/markets/sp500-rally","metadata":{"sp500":"+4.2%","nvda":"+6.1%"}}'),
('f1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c7', 4, 'complete', 'OpenAI has launched GPT-5 Enterprise with real-time reasoning and native tool-use capabilities. Early adopters report a 40 percent reduction in workflow automation time. This could reshape our internal tooling strategy.', 'https://picsum.photos/seed/ai-neural-lab/1280/720', '{"is_active":true,"card_type":"link_open","title":"GPT-5 Enterprise","action_button_text":"Read Analysis","action_payload":"https://techcrunch.com/2026/03/gpt5-enterprise","metadata":{"model":"GPT-5","speed":"10x"}}'),
('f1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c7', 5, 'complete', 'Two pull requests need attention. Chen submitted a major OAuth 2.1 refactor with 47 files changed adding PKCE support and token rotation. Priya delivered a dashboard optimization with a 3x performance improvement. Also, a payment service incident hit 2.3 percent error rates but has been mitigated.', 'https://picsum.photos/seed/dev-workspace/1280/720', '{"is_active":true,"card_type":"link_open","title":"Review Pull Requests","action_button_text":"Open GitHub","action_payload":"https://github.com/org/platform/pulls","metadata":{"pending_prs":2}}'),
('f1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c7', 6, 'complete', 'Priority email from CFO Sarah Chen: the Q1 board deck is ready for your final review. Revenue up 23 percent year over year, customer acquisition cost down 15 percent, runway extended to 28 months. She needs your sign-off before 5 PM today.', 'https://picsum.photos/seed/exec-office/1280/720', '{"is_active":true,"card_type":"approval","title":"Q1 Board Deck Review","action_button_text":"Review and Approve","action_payload":"mailto:sarah.chen@company.com","metadata":{"revenue":"+23%","runway":"28 months"}}'),
('f1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c7', 7, 'complete', 'Snowflake VP of Partnerships has proposed a strategic data integration co-build that would give us access to their 9,800 enterprise customers. The business development team has an initial call scheduled for Thursday.', 'https://picsum.photos/seed/conference-handshake/1280/720', '{"is_active":true,"card_type":"calendar_join","title":"Snowflake Partnership Call","action_button_text":"Join Thursday Call","action_payload":"https://zoom.us/j/partnership","metadata":{"partner":"Snowflake","reach":"9800+"}}'),
('f1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c7', 8, 'complete', 'The ML team just set a new company record. Recommendation model accuracy hit 96.7 percent, up from 94.2 percent. They are six weeks ahead of Q2 targets. On hiring, two of three senior engineer offers have been accepted with fifteen candidates in final rounds.', 'https://picsum.photos/seed/team-celebrate/1280/720', '{"is_active":true,"card_type":"summary","title":"Team Performance","action_button_text":"View Details","action_payload":"/team","metadata":{"ml_accuracy":"96.7%","hiring":"2/3 accepted"}}'),
('f1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c7', 9, 'complete', 'Customer escalation: Acme Corp, a 450 thousand dollar ARR account, is experiencing 30-minute delays in their data sync pipeline. They have a board presentation tomorrow. Engineering is investigating. Production deploy v3.14.2 completed successfully with all health checks passing.', 'https://picsum.photos/seed/server-room-amber/1280/720', '{"is_active":true,"card_type":"link_open","title":"Acme Corp Escalation","action_button_text":"View Incident","action_payload":"https://slack.com/escalations","metadata":{"customer":"Acme Corp","arr":"$450K"}}'),
('f1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c7', 10, 'complete', 'Regulatory note: the EU AI Act has entered enforcement. You have six months to complete risk assessments with fines up to 35 million euros. Flag this for legal review. That is your briefing for March 22nd. Ten signals processed, four actions pending your decision. Execute with precision.', 'https://picsum.photos/seed/executive-desk-morning/1280/720', '{"is_active":true,"card_type":"summary","title":"Actions Pending","action_button_text":"View Action Items","action_payload":"/your-brief","metadata":{"signals":10,"pending":4}}');