INSERT INTO briefing_scripts (id, user_id, persona, trigger, title, script_json) VALUES (
  'e1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c6',
  '00000000-0000-0000-0000-000000000000',
  'Executive Briefer',
  'manual',
  'Morning Brief — March 22, 2026',
  jsonb_build_object(
    'script_metadata', jsonb_build_object('persona_applied', 'Executive Briefer', 'total_estimated_segments', 10),
    'timeline_segments', jsonb_build_array(
      jsonb_build_object('segment_id', 1, 'segment_type', 'opening', 'dialogue', 'Good morning. It is Saturday, March 22nd. Clear skies, seventy-two degrees expected today. Winds light from the southwest. A strong day to move decisively — here is your operational briefing.', 'grounding_source_id', 'weather_daily_2', 'runware_b_roll_prompt', 'Golden hour sunrise over modern city skyline with glass towers reflecting warm light', 'ui_action_card', jsonb_build_object('is_active', true, 'card_type', 'summary', 'title', 'Morning Situation Report', 'action_button_text', 'View Full Brief', 'action_payload', '/your-brief', 'metadata', jsonb_build_object('temp', '72F', 'condition', 'Clear'))),
      jsonb_build_object('segment_id', 2, 'segment_type', 'security', 'dialogue', 'Critical security alert: a zero-day authentication bypass has been disclosed in NextAuth.js, CVE-2026-4521, with a CVSS score of 9.8. Over twelve thousand applications are affected. Patches are available. Your security team should prioritize this immediately.', 'grounding_source_id', 'news_cybersec_2', 'runware_b_roll_prompt', 'Dark cybersecurity operations center with blue-lit monitoring screens showing threat dashboards', 'ui_action_card', jsonb_build_object('is_active', true, 'card_type', 'link_open', 'title', 'Critical CVE Alert', 'action_button_text', 'Review Advisory', 'action_payload', 'https://thehackernews.com/2026/03/nextauth-zero-day', 'metadata', jsonb_build_object('cve', 'CVE-2026-4521', 'cvss', '9.8'))),
      jsonb_build_object('segment_id', 3, 'segment_type', 'market', 'dialogue', 'Markets are surging. The S and P 500 hit an all-time high, driven by a 4.2 percent rally in AI stocks. NVIDIA is up 6.1 percent, Microsoft up 3.8 percent. Analysts point to aggressive AI infrastructure spending as the primary catalyst.', 'grounding_source_id', 'news_market_rally_2', 'runware_b_roll_prompt', 'Professional trading floor with multiple screens showing upward trending charts and green indicators', 'ui_action_card', jsonb_build_object('is_active', true, 'card_type', 'link_open', 'title', 'Market Rally Analysis', 'action_button_text', 'Open Bloomberg', 'action_payload', 'https://bloomberg.com/markets/sp500-rally', 'metadata', jsonb_build_object('sp500', '+4.2%', 'nvda', '+6.1%'))),
      jsonb_build_object('segment_id', 4, 'segment_type', 'ai_insights', 'dialogue', 'OpenAI has launched GPT-5 Enterprise with real-time reasoning and native tool-use capabilities. Early adopters report a 40 percent reduction in workflow automation time. This could reshape our internal tooling strategy.', 'grounding_source_id', 'news_ai_breakthrough_2', 'runware_b_roll_prompt', 'Futuristic AI laboratory with neural network visualizations flowing across transparent displays', 'ui_action_card', jsonb_build_object('is_active', true, 'card_type', 'link_open', 'title', 'GPT-5 Enterprise', 'action_button_text', 'Read Analysis', 'action_payload', 'https://techcrunch.com/2026/03/gpt5-enterprise', 'metadata', jsonb_build_object('model', 'GPT-5', 'speed', '10x'))),
      jsonb_build_object('segment_id', 5, 'segment_type', 'engineering', 'dialogue', 'Two pull requests need attention. Chen submitted a major OAuth 2.1 refactor with 47 files changed adding PKCE support and token rotation. Priya delivered a dashboard optimization with a 3x performance improvement. Also, a payment service incident hit 2.3 percent error rates but has been mitigated.', 'grounding_source_id', 'pr_auth_refactor_2', 'runware_b_roll_prompt', 'Modern developer workspace with dual monitors showing code review interface and CI pipeline', 'ui_action_card', jsonb_build_object('is_active', true, 'card_type', 'link_open', 'title', 'Review Pull Requests', 'action_button_text', 'Open GitHub', 'action_payload', 'https://github.com/org/platform/pulls', 'metadata', jsonb_build_object('pending_prs', 2))),
      jsonb_build_object('segment_id', 6, 'segment_type', 'email_item', 'dialogue', 'Priority email from CFO Sarah Chen: the Q1 board deck is ready for your final review. Revenue up 23 percent year over year, customer acquisition cost down 15 percent, runway extended to 28 months. She needs your sign-off before 5 PM today.', 'grounding_source_id', 'email_investor_2', 'runware_b_roll_prompt', 'Executive office with laptop showing financial presentation charts and warm ambient lighting', 'ui_action_card', jsonb_build_object('is_active', true, 'card_type', 'approval', 'title', 'Q1 Board Deck Review', 'action_button_text', 'Review and Approve', 'action_payload', 'mailto:sarah.chen@company.com', 'metadata', jsonb_build_object('revenue', '+23%', 'runway', '28 months'))),
      jsonb_build_object('segment_id', 7, 'segment_type', 'partnerships', 'dialogue', 'Snowflake VP of Partnerships has proposed a strategic data integration co-build that would give us access to their 9,800 enterprise customers. The business development team has an initial call scheduled for Thursday.', 'grounding_source_id', 'email_partnership_2', 'runware_b_roll_prompt', 'Modern glass conference room with two teams shaking hands and city view in background', 'ui_action_card', jsonb_build_object('is_active', true, 'card_type', 'calendar_join', 'title', 'Snowflake Partnership Call', 'action_button_text', 'Join Thursday Call', 'action_payload', 'https://zoom.us/j/partnership', 'metadata', jsonb_build_object('partner', 'Snowflake', 'reach', '9800+'))),
      jsonb_build_object('segment_id', 8, 'segment_type', 'team_updates', 'dialogue', 'The ML team just set a new company record. Recommendation model accuracy hit 96.7 percent, up from 94.2 percent. They are six weeks ahead of Q2 targets. On hiring, two of three senior engineer offers have been accepted with fifteen candidates in final rounds.', 'grounding_source_id', 'slack_ml_win_2', 'runware_b_roll_prompt', 'Team of engineers celebrating in a modern open office with dashboards showing upward metrics', 'ui_action_card', jsonb_build_object('is_active', true, 'card_type', 'summary', 'title', 'Team Performance', 'action_button_text', 'View Details', 'action_payload', '/team', 'metadata', jsonb_build_object('ml_accuracy', '96.7%', 'hiring', '2/3 accepted'))),
      jsonb_build_object('segment_id', 9, 'segment_type', 'ops_alert', 'dialogue', 'Customer escalation: Acme Corp, a 450 thousand dollar ARR account, is experiencing 30-minute delays in their data sync pipeline. They have a board presentation tomorrow. Engineering is investigating. Production deploy v3.14.2 completed successfully with all health checks passing.', 'grounding_source_id', 'slack_escalation_2', 'runware_b_roll_prompt', 'Server room with blinking status lights and one rack highlighted in amber warning color', 'ui_action_card', jsonb_build_object('is_active', true, 'card_type', 'link_open', 'title', 'Acme Corp Escalation', 'action_button_text', 'View Incident', 'action_payload', 'https://slack.com/escalations', 'metadata', jsonb_build_object('customer', 'Acme Corp', 'arr', '$450K'))),
      jsonb_build_object('segment_id', 10, 'segment_type', 'closing', 'dialogue', 'Regulatory note: the EU AI Act has entered enforcement. You have six months to complete risk assessments with fines up to 35 million euros. Flag this for legal review. That is your briefing for March 22nd. Ten signals processed, four actions pending your decision. Execute with precision.', 'grounding_source_id', 'news_regulation_2', 'runware_b_roll_prompt', 'Elegant executive desk with tablet showing a clean checklist and morning coffee with city panorama through window', 'ui_action_card', jsonb_build_object('is_active', true, 'card_type', 'summary', 'title', 'Actions Pending', 'action_button_text', 'View Action Items', 'action_payload', '/your-brief', 'metadata', jsonb_build_object('signals', 10, 'pending', 4)))
    )
  )
) ON CONFLICT (id) DO UPDATE SET script_json = EXCLUDED.script_json, title = EXCLUDED.title;